version: '1.1'

stages:
- stage:
  - git-checkout:

- stage:
  - release:
      params:
        dice_yml: ${git-checkout}/dice.yml

- stage:
  - dice:
      params:
        release_id: ${release:OUTPUT:releaseID}
