spring:
  application.name: dubbo-spring-boot-provider
server:
  port: 8089
dubbo:
  application.name: dubbo-spring-boot-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://${NACOS_ADDRESS:127.0.0.1:8848}?namespace=${NACOS_TENANT_ID:}
  scan:
    base-packages: io.terminus.dice.trial.demo.hellodubbo