spring:
  application.name: dubbo-spring-boot-consumer
server:
  port: 8088
dubbo:
  application.name: dubbo-spring-boot-consumer
  registry:
    address: nacos://${NACOS_ADDRESS:127.0.0.1:8848}?namespace=${NACOS_TENANT_ID:}